services:
  terra-vision-ai-mongo:
    image: mongo:8.2.4
    container_name: terra-vision-ai-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${TERRA_VISION_AI_MONGO_DB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${TERRA_VISION_AI_MONGO_DB_ROOT_PASSWORD}
    volumes:
      - terra-vision-ai-mongo-db-volume:/data/db
      - terra-vision-ai-mongo-configdb-volume:/data/configdb
      - ./terra-vision-ai-mongo-init.js://docker-entrypoint-initdb.d/terra-vision-ai-mongo-init.js:ro
    networks:
      - terra-vision-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  terra-vision-ai-mongo-express:
    image: mongo-express:1.0.2
    container_name: terra-vision-ai-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: terra-vision-ai-mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${TERRA_VISION_AI_MONGO_DB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${TERRA_VISION_AI_MONGO_DB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: ${TERRA_VISION_AI_MONGO_EXPRESS_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${TERRA_VISION_AI_MONGO_EXPRESS_USERNAME}
    depends_on:
      terra-vision-ai-mongo:
        condition: service_healthy
    networks:
      - terra-vision-network

networks:
  terra-vision-network:
    driver: bridge
    name: terra-vision-network


volumes:
  terra-vision-ai-mongo-db-volume:
    name: terra-vision-ai-mongo-db-volume

  terra-vision-ai-mongo-configdb-volume:
    name: terra-vision-ai-mongo-configdb-volume
  