services:
    terra-vision__mongo:
        image: mongo:8.2.4
        container_name: terra-vision__mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${TERRA_VISION__MONGO__ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${TERRA_VISION__MONGO__ROOT_PASSWORD}
        volumes:
            - terra-vision__mongo__db-volume:/data/db
            - terra-vision__mongo__configdb-volume:/data/configdb
            - ./mongo/initdb:/docker-entrypoint-initdb.d:ro
        networks:
            - terra-vision-network

    terra-vision__redis:
        image: redis:8.2.4
        container_name: terra-vision__redis
        ports:
            - "6379:6379"
        command: redis-server --requirepass ${TERRA_VISION__REDIS__PASSWORD}
        volumes:
            - terra-vision__redis__data-volume:/data
        networks:
            - terra-vision-network
    
    terra-vision__postgres:
        image: postgres:18.2
        container_name: terra-vision__postgres
        restart: always
        environment:
            POSTGRES_USER: ${TERRA_VISION__POSTGRES__USER}
            POSTGRES_PASSWORD: ${TERRA_VISION__POSTGRES__PASSWORD}
            POSTGRES_DB: ${TERRA_VISION__POSTGRES__DB} # default db
        ports:
            - '5432:5432'
        volumes:
            - terra-vision__postgres__volume:/var/lib/postgresql
            - ./postgresql/initdb:/docker-entrypoint-initdb.d:ro
        networks:
            - terra-vision-network

    terra-vision__minio:
        image: minio/minio:RELEASE.2025-09-07T16-13-09Z
        container_name: terra-vision__minio
        restart: unless-stopped
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${TERRA_VISION__MINIO__ROOT_USER}
            MINIO_ROOT_PASSWORD: ${TERRA_VISION__MINIO__ROOT_PASSWORD}
        volumes:
            - terra-vision__minio__data-volume:/data
        command: server /data --console-address ":9001"
        networks:
            - terra-vision-network

networks:
    terra-vision-network:
        driver: bridge
        name: terra-vision-network

volumes:
    terra-vision__mongo__db-volume:
        name: terra-vision__mongo__db-volume

    terra-vision__mongo__configdb-volume:
        name: terra-vision__mongo__configdb-volume
    
    terra-vision__redis__data-volume:
        name: terra-vision__redis__data-volume
    
    terra-vision__postgres__volume:
        name: terra-vision__postgres__volume
    
    terra-vision__minio__data-volume:
        name: terra-vision__minio__data-volume

