# YAML anchor — not a Spring Boot property, used for reuse only
anchors:
  gateway-filters:
    common-cookie-config: &commonCookieConfig
      domain: localhost
      rootPath: /
      refreshPath: /api/auth/refresh
      sameSite: Lax
      secure: false


spring:
  application:
    name: terra-vision-gateway

  data:
    redis:
      host: localhost
      port: 6379
      password: ${TERRA_VISION__REDIS__PASSWORD}

  config:
    import: "vault://"

  cloud:
    vault:
      uri: http://localhost:8200
      authentication: token
      token: ${VAULT_TOKEN:my-root-token}
      kv:
        enabled: true
        backend: secret

    gateway:
      server:
        webflux:
          routes:

            # ------ Auth microservice: Login ------
            - id: auth-service-login
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/login
              filters:
                - name: AuthenticationResponseToTokenCookies # AuthenticationResponseToTokenCookiesGatewayFilterFactory
                  args:
                    <<: *commonCookieConfig # Injects the common config here

              # ------ Auth microservice: Refresh ------
            - id: auth-service-refresh
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/refresh
              filters:
                # RefreshTokenCookieToRequestBodyTransformationGatewayFilterFactory
                # name: ClearAuthCookiesOnLogoutGatewayFilterFactory without GatewayFilterFactory
                - name: RefreshTokenCookieToRequestBodyTransformation

                # AuthenticationResponseToTokenCookiesGatewayFilterFactory
                # name: ClearAuthCookiesOnLogoutGatewayFilterFactory without GatewayFilterFactory
                - name: AuthenticationResponseToTokenCookies
                  args:
                    <<: *commonCookieConfig # Injects the common config here

            # ------ Auth microservice: Logout ------
            - id: auth-service-logout
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/logout
              filters:
                # ClearAuthCookiesOnLogoutGatewayFilterFactory
                # name: ClearAuthCookiesOnLogoutGatewayFilterFactory without GatewayFilterFactory
                - name: ClearAuthCookiesOnLogout
                  args:
                    <<: *commonCookieConfig # Injects the common config here

            # ------ Auth microservice routes ------
            - id: auth-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/**

            # ------ AI microservice routes ------
            - id: ai-service
              uri: http://localhost:8000
              predicates:
                - Path=/api/ai/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/api/auth/.well-known/jwks.json
          issuer-uri: terra-vision.com # must match what auth service puts in token as 'issuer' claim. For example http://localhost:8080 or http://localhost:8082 or terra-vision.com

logging:
  level:
    com.project.terravision.gateway: debug

application:
  security:
    allowed-origins:
      - http://localhost:5173
  services:
    auth-service:
      url: http://localhost:8080