spring:
  application:
    name: terra-vision-gis

  config:
    import: "vault://"

  cloud:
    vault:
      uri: http://localhost:8200
      authentication: token
      token: ${VAULT_TOKEN:my-root-token}
      kv:
        enabled: true
        backend: secret

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/terra_vision_gis_db
    username: ${TERRA_VISION__POSTGIS__USER}
    password: ${TERRA_VISION__POSTGIS__PASSWORD}

server:
  port: 8083

application:

  minio:
    url: http://localhost:9000
    access-key: ${TERRA_VISION__MINIO__ROOT_USER}
    secret-key: ${TERRA_VISION__MINIO__ROOT_PASSWORD}
    bucket: terra-vision-gis-bucket