spring:
  application:
    name: terra-vision-auth

server:
  port: 8082

app:
  security:
    allowed-origins:
      - http://localhost:5173
    jwt:
      issuer: http://localhost:8080
    key-pair:
      size: 2048